# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nmslib_idx_dist <- function(input_list, k, threads = 1L) {
    .Call(`_nmslibR_nmslib_idx_dist`, input_list, k, threads)
}

y_idxs <- function(idxs, y, threads = 1L) {
    .Call(`_nmslibR_y_idxs`, idxs, y, threads)
}

check_NaN_Inf <- function(x) {
    .Call(`_nmslibR_check_NaN_Inf`, x)
}

